### ISSUE TITLE
eikonalfm.distance yields transposed distance matrix

### ISSUE THREAD

**Issue by martijnende** [kevinganster/eikonalfm#2]
The [PyPI example](https://pypi.org/project/eikonalfm/) states that the final solution of the factored Eikonal equation can be obtained as the element-wise product between `tau1` and `tau0`:

```
tau1_ffm = eikonalfm.factored_fast_marching(c, x_s, dx, order)
tau0 = eikonalfm.distance(tau1_ffm.shape, dx, x_s)

tau = tau0 * tau1_ffm
```

For an input shape `c.shape = (A, B)`, we get `tau1_ffm.shape = (A, B)` but `tau0.shape = (B, A)` (i.e., `tau0` is transposed). I confirm that `tau = tau0.T * tau1_ffm` yields the correct results.

(`eikonalfm.__version__ = 0.9.5`)

**Comment by kevinganster** [comment]
That has to do with the indexing method used. By default, the `distance`-method uses the same indexing as `np.meshgrid` does (i.e. `indexing="xy"`). If you want `tau0.shape = (A, B)`, you should use `indexing="ij"`.
But you are absolutely right that the PyPi example is misleading and simply wrong. I will fix that soon.
The correct code would be
```
tau1_ffm = eikonalfm.factored_fast_marching(c, x_s, dx, order)
tau0 = eikonalfm.distance(tau1_ffm.shape, dx, x_s, indexing="ij")

tau = tau0 * tau1_ffm
```
The other question is, if the default value of `indexing` should rather be `"ij"`. I will think about that.
